######################################################################################################
# This file is generated when `botfront up` is invoked.                                              #
# Changes in .botfront/botfront.yml and .botfront/docker-compose-template.yml will be reflected here #
######################################################################################################

version: '3.0'
services:
  botfront:
    image: 'botfront/botfront:v1.0.5'
    container_name: botfront-app
    restart: always
    networks:
      - botfront-network
    volumes:
      - './models/:/app/models'
    ports:
      - '8888:3000'
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      PORT: 3000
    user: root
  rasa:
    image: teploeodealko/rasa-for-botfront:2.3.3-e8-1.2.1
    container_name: botfront-rasa1
    networks:
      - botfront-network
    restart: always
    ports:
      - '5005:5005'
    volumes:
      - './models/:/app/models'
    env_file:
      - .env
    environment:
      - BF_PROJECT_ID=saQz9NBoG3R8rE5Mk
    user: root
  actions:
    build:
      context: ./actions
      args:
        RASA_SDK_IMAGE: '${IMAGES_CURRENT_ACTIONS}'
    container_name: botfront-actions
    networks:
      - botfront-network
    restart: always
    ports:
      - '5055:5055'
    volumes:
      - './actions:/app/actions'
    command:
      - start
      - '--debug'
      - '--actions'
      - actions
    env_file:
      - .env
    environment:
      - BF_PROJECT_ID=saQz9NBoG3R8rE5Mk
    user: root
  duckling:
    image: 'botfront/duckling:latest'
    container_name: botfront-duckling
    networks:
      - botfront-network
    restart: always
    ports:
      - '8000:8000'
  mongo:
    image: 'mongo:latest'
    container_name: botfront-mongo
    restart: always
    networks:
      - botfront-network
    volumes:
      - './botfront-db:/data/db'
    ports:
      - '27017:27017'
    env_file:
      - .env
    user: root
networks:
  botfront-network: {}
volumes:
  botfront-db: null
